import { RouteInfo } from './sidebar.metadata';

export const ROUTES: RouteInfo[] = [
  {
    path: '',
    title: 'General Information',
    icon: '',
    class: 'nav-small-cap',
    label: '',
    labelClass: '',
    extralink: true,
    submenu: [],
  },
  {
    path: '/dashboard',
    title: 'Dashboard',
    icon: 'mdi mdi-gauge',
    class: '',
    label: '',
    labelClass: '',
    extralink: false,
    submenu: [],
  },
  {
    path: '',
    title: 'Personal Features',
    icon: '',
    class: 'nav-small-cap',
    label: '',
    labelClass: '',
    extralink: true,
    submenu: [],
  },
  {
    path: '/dashboard/projects',
    title: 'Projects',
    icon: 'mdi mdi-folder-multiple',
    class: '',
    label: '',
    labelClass: '',
    extralink: false,
    submenu: [],
  },
  {
    path: '/dashboard/skills',
    title: 'Skills',
    icon: 'mdi mdi-folder-star',
    class: '',
    label: '',
    labelClass: '',
    extralink: false,
    submenu: [],
  },
  {
    path: '/dashboard/services',
    title: 'Services',
    icon: 'mdi mdi-lightbulb-on-outline',
    class: '',
    label: '',
    labelClass: '',
    extralink: false,
    submenu: [],
  },
  {
    path: '/dashboard/experience',
    title: 'Experience',
    icon: 'mdi mdi-account-card-details',
    class: '',
    label: '',
    labelClass: '',
    extralink: false,
    submenu: [],
  },
  {
    path: '/dashboard/education',
    title: 'Education',
    icon: 'mdi mdi-school',
    class: '',
    label: '',
    labelClass: '',
    extralink: false,
    submenu: [],
  },
  {
    path: '/dashboard/phone-numbers',
    title: 'Phone Numbers',
    icon: 'mdi mdi-phone-forward',
    class: '',
    label: '',
    labelClass: '',
    extralink: false,
    submenu: [],
  },
  {
    path: '/dashboard/social-networks',
    title: 'Social Networks',
    icon: 'mdi mdi-facebook',
    class: '',
    label: '',
    labelClass: '',
    extralink: false,
    submenu: [],
  },
];
